//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebAppEC.br.com.webint.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CGatewayPagamentoSoap", Namespace="http://www.webint.com.br/")]
    public partial class CGatewayPagamento : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validarCartaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CGatewayPagamento() {
            this.Url = global::WebAppEC.Properties.Settings.Default.WebAppEC_br_com_webint_www_CGatewayPagamento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validarCartaoCompletedEventHandler validarCartaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webint.com.br/validarCartao", RequestNamespace="http://www.webint.com.br/", ResponseNamespace="http://www.webint.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validarCartao(string strNomeImpresso, string strNumeroCartao, string strVencimento, string strCodSeguranca, double dblValor, int intParcelas) {
            object[] results = this.Invoke("validarCartao", new object[] {
                        strNomeImpresso,
                        strNumeroCartao,
                        strVencimento,
                        strCodSeguranca,
                        dblValor,
                        intParcelas});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarCartaoAsync(string strNomeImpresso, string strNumeroCartao, string strVencimento, string strCodSeguranca, double dblValor, int intParcelas) {
            this.validarCartaoAsync(strNomeImpresso, strNumeroCartao, strVencimento, strCodSeguranca, dblValor, intParcelas, null);
        }
        
        /// <remarks/>
        public void validarCartaoAsync(string strNomeImpresso, string strNumeroCartao, string strVencimento, string strCodSeguranca, double dblValor, int intParcelas, object userState) {
            if ((this.validarCartaoOperationCompleted == null)) {
                this.validarCartaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarCartaoOperationCompleted);
            }
            this.InvokeAsync("validarCartao", new object[] {
                        strNomeImpresso,
                        strNumeroCartao,
                        strVencimento,
                        strCodSeguranca,
                        dblValor,
                        intParcelas}, this.validarCartaoOperationCompleted, userState);
        }
        
        private void OnvalidarCartaoOperationCompleted(object arg) {
            if ((this.validarCartaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarCartaoCompleted(this, new validarCartaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void validarCartaoCompletedEventHandler(object sender, validarCartaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarCartaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarCartaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591